theme: jekyll-theme-minimal
title: PS2 Modchip Tutorials
description: Show your superiority of FMCB and PS2BBL!
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Setup
    url: setup
