site_name: PS2 Modchip Tutorials
site_url: https://ps2modchiptutorials.com

theme:
  name: material
  custom_dir: overrides
  language: en 
  font:
    text: Oxanium
    code: Roboto Mono
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/website_logo1.png
  favicon: assets/favicon.png
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - toc.follow
#    - toc.integrate
  icon:
    admonition:
      soldering: material/soldering-iron

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - blog
  - glightbox

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  
extra:
  social:
  - icon: /fontawesome/regular/envelope
    name: send me an email
    link: mailto:info@ps2modchiptutorials.com
  - icon: fontawesome/brands/x-twitter
    name: R3Z3N on X
    link: https://x.com/rezenclowd3
  - icon: fontawesome/brands/youtube
    name: PS2 Modchip Tutorials on YouTube
    link: https://www.youtube.com/@PS2ModchipTutorials

# Page tree
nav:
  - Home: index.md
  - Crystal Chips:
    - crystal-chips/cc-index.md
    - 1.0 Install Diagrams: crystal-chips/cc10-install.md
    - 1.1+ Install Diagrams: crystal-chips/cc-install.md
    - Video Tutorials: crystal-chips/cc-vids.md
    - Written Tutorials: crystal-chips/cc-writeups.md
    - Files: crystal-chips/cc-files.md
    - PBT Scripting: crystal-chips/cc-scripting.md
    - Archived Website: crystal-chips/cc-archived.md
  - DMS4:
    - dms4/index.md
    - Install Diagrams: dms4/dms4-install.md
    - Video Tutorials: dms4/dms4-vids.md
    - Written Tutorials: dms4/dms4-writeups.md
    - Files: dms4/dms4-files.md
    - Archived Website: dms4/dms4-archived.md
  - Ghost 2:
    - ghost2/index.md
    - Install Diagrams: ghost2/ghost2-install.md
    - Video Tutorials: ghost2/ghost2-vids.md
    - Written Tutorials: ghost2/ghost2-writeups.md
    - Files: ghost2/ghost2-files.md
    - Archived Website: ghost2/ghost2-archived
  - Matrix Infinity and clones:
    - mi/index.md
    - Install Diagrams: mi/mi-install.md
    - Video Tutorials: mi/mi-vids.md
    - Written Tutorials: mi/mi-writeups.md
    - Files: mi/mi-files.md
    - Archived Website: mi/mi-archived.md
  - Recommended Accessories:
    - misc/index.md
    - Matrix Picfix: misc/picfix.md
  - Thanks and Links: thanks.md
  - Blog:
    - blog/index.md




    